version: '2'

services:

  resume:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: mastak/prioritizator:latest
    volumes:
      - .:/usr/src/resume
    environment:
      - DEBUG=1
    ports:
      - "8000:8000"
